config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
 attribute :message,		:validate => true
  attribute :nickname,  :captcha  => true



  def headers 
  	{
  	:subject => "Contact Form",
  	:to => "swollenseal@mail.ru",
  	:from => %("#{name}"  <#{email}>)
}
end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
	 extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver 
			flash.now[:error] = nil
		else 
			flash.now[:error] = "Cannot send message."
			render :new 
		end
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page:4)
	end


	def new
		@post = Post.new
	end


	def create
		@post = Post.new post_params


		if @post.save
			redirect_to @post, notice: "Hell yeah, Kirill! This article was succesfully saved!"
		else 
			render 'new', notice: "Oh no! I was unable to save your post."
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Hey! Article was saved!"
		else 
			render 'edit'
		end
	end


	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private 

	def post_params
		params.require(:post).permit(:title, :content, :slug )
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

before_action :find_project, only: [:show, :edit, :update, :destroy]

	def index
		@projects = Project.all.order('created_at desc ')
	end


	def new
		@project = Project.new
	end

	def create
		@project = Project.new project_params

		if @project.save
			redirect_to @project, notice: "Okay, project was saved."
		else 
			render new
		end
	end

	def show

	end


	def edit

	end

	def update
		if @project.update project_params
			redirect_to @project, notice: "Okay, project was updated."
		else 
			render 'edit'
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end



	private  

	def find_project
		@project = Project.friendly.find(params[:id])
	end


	def project_params
		params.require(:project).permit(:title, :description, :link, :slug)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("Created_at desc");
		@projects = Project.all.limit(3).order("Created_at desc");
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code, language)
			Pygments.highlight(code, lexer: language)
		end
	end
	def markdown(content)
		renderer  = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks:true,
			strikethrought:true,
			superscript:true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe;
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title"> Contact Me </h1>
<div class="skinny_wrapper wrapper_padding">
	<h1>Thank you for Your message!</h1>
	<p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title"> Contact </h1>

<div class="skinny_wrapper wrapper_padding">

	<%= form_for @contact do |f| %>
	<%= f.label :name %> <br>
	<%= f.text_field :name, required: true %>


	<br>


	<%= f.label :email %> <br>
	<%= f.text_field :email, required: true %>

	<br>


	<%= f.label :message %> <br>
	<%= f.text_area :message, as: :text %>


	<div class="hidden">
		<%= f.label :nickname %> <br>
		<%= f.text_field :nickname, hint: 'Leave this field blank' %>
	</div>


	<%= f.submit 'Send Message', class: "button" %>

	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>WEB-developer  &amp; Designer</title>
	<meta name="description" content="">

	<script src="libs/modernizr/modernizr.js"></script>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

			<header id="main_navigation" class="clearfix">
				<%= link_to "Something on the way", root_path, class: "name" %>

				<nav>
					<%= link_to "Blog", posts_path %>

					<%= link_to "Projects", projects_path %>


					<a href="contact.html">Contact </a>
				</nav>

			</header>

			<%= yield %>

			<div class="footer">
				<footer id="main_footer" class="site-footer">
					<p class="copyright">&copy; 2016 Kirill </p>
					<nav>
					<a href="#" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a>
						<a href="#"><i class="fa fa-git" aria-hidden="true"></i></a>
						<a href="#"><i class="fa fa-vk" aria-hidden="true"></i></a>
					</nav>
				</footer>
			</div>
	


	</body>
	</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/

var disqus_config = function () {
this.page.url = '<%= url_for([@post, {only_path: false}]) %>'; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//myblogfirstlearn.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
<ul>
<% @post.errors.full_messages.each do |msg| %>
<li> <%= msg %> </li>
<% end %>
</ul>
<% end %>

<%= f.label :title %> <br>
<%= f.text_field :title %>
<br>
<br>

<%= f.label :content, "Write your article here" %><br>
<%= f.text_area :content %>
<br>
<br>


<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1 id="page_title"> Stuff Notes</h1>

	<div id="post-wrapper" class ="skinny_wrapper">
 
	<%  @posts.each do |post| %>
	<div class="post">
		<p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
		<h2><a href="article_show.html"> <%= link_to post.title, post %></a></h2>

		<hr>
		</div>
		<% end %>
		</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
	<p class="date"><%= @post.created_at.strftime('%A. %B %d') %></p>
	<h1> <%=  @post.title %> </h1>
	<hr>
	</header>

	<div id="content">
	<%= markdown @post.content %>
	</div>
<hr>
	<div id="share_box">
		<p>Share my post : </p>
		<!-- twitter -->
		<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @kiri;; = &amp;url=<%= url_for([@post, {only_path: false}]) %>','_blank', 'width=800, height=500, top=200, left=300');void(0);">
		<i class="fa fa-twitter"></i></a>

		<!-- VK -->

		<a  onclick="javascript:window.open('http://vkontakte.ru/share.php?=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-vk"></i></a>

		<!-- Facebook  -->
		<a  onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>


		<!-- Google + -->
		<a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
	</div>

	
	<hr>

<%= render 'disqus' %>


</div>

<%= link_to "Edit", edit_post_path(@post) %>





<!-- 
<%= @post.title %><br>
<%= @post.content %> -->

<!-- <br>
<br>

<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete, data:{confirm: "Are you sure? Delete this post?"} %> -->

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<% if @project.errors.any? %>
<h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
<ul>
<% @project.errors.full_messages.each do |msg| %>
<li> <%= msg %> </li>
<% end %>
</ul>
<% end %>

<%= f.label :title %> <br>
<%= f.text_field :title %>
<br>
<br>

<%= f.label :description %><br>
<%= f.text_area :description %>
<br>
<br>


<%= f.label :link %> <br>
<%= f.text_field :link %>
<br>
<br>

<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1> Edit Project</h1>
	<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title"> Stuff I've built</h1>


	<div id="post-wrapper" class ="skinny_wrapper">
 	<%  @projects.each do |project| %>
	<div class="post">
		<p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
		<h2><a href="article_show.html"> <%= link_to project.title, project %></a></h2>

		<hr>
		</div>
		<% end %>
		</div>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
	<h1>New Project</h1>
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @project.created_at.strftime('%A. %B %d') %></p>
		<h1> <%=  @project.title %> </h1>
		<hr>
	</header>

	<div id="content">
		<%= markdown @project.description %>

		<div class="button_wrapper">
			<a href="<%= @project.link%>" class="project_button" target="_blank"> Visit <%= @project.title %> </a>
		</div>
	</div>

	<%= link_to "Edit", edit_project_path(@project) %>
	<%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?"} %>
	<hr>
</div>

app/views/welcome/index.html.erb
			<div class="page-wrap">
			<div class="wrapper-inner  wrapper-padding clearfix">
				<div class="col-1 homepage_content">
					<h2> About me </h2>
					<hr>
					<p>This is my training application. Just for expierence and testing. ;) </p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia eum suscipit, mollitia non. Sequi nesciunt recusandae eius non quos laboriosam, ducimus provident veritatis et soluta. Exercitationem necessitatibus laborum pariatur voluptates.Thundercats roof party health goth chartreuse bitters, locavore tacos microdosing yr sartorial meggings paleo wolf. Cliche vegan selfies farm-to-table, drinking vinegar dreamcatcher lo-fi keffiyeh salvia pabst cray jean shorts banh mi disrupt. Biodiesel cronut bespoke green juice four dollar toast actually. Whatever freegan ramps, pug flexitarian polaroid deep v tote bag cred sartorial small batch. Biodiesel fashion axe normcore tofu wolf yuccie pickled lomo PBR&B, vegan farm-to-table venmo 90's wayfarers. Food truck drinking vinegar vice ramps craft beer readymade.</p>
				</div>
				<div class="col-2 homepage_content">
					<h2> What i do? </h2>
					<hr>

					<% @posts.each do |post| %>
					<h3><a href="#"> <%= link_to post.title, post %> </a> </h3>
					<p class="date" > <%= post.created_at.strftime("%A, %b %d") %> </p>
					<% end %>
				


				</div>

				<div class="col-3 homepage_content">
					<h2> What i built? </h2>
					<hr>
						<% @projects.each do |project| %>
					<h3><a href="#"> <%= link_to project.title, project %> </a> </h3>
					<p class="date" > <%= project.created_at.strftime("%A, %b %d") %> </p>
					<% end %>

				</div>

			</div>
</div>